#!/bin/bash
# Run ONCE on a Rorqual login node (needs internet -- compute nodes have
# none) to set up everything preprocess_rorqual.slurm jobs depend on:
#   - a venv with the project installed
#   - backbone weights, in an explicit directory (not the hidden HF cache)
#   - the rorqual_vjepa_clip{10,30,90}.yaml configs, generated from cc_config.sh
#     so paths only need to be edited in one place
#   - the LPT-balanced shard files under shards/, shared by all three scales
#
# Safe to re-run: venv creation and weight downloads are both skip-if-present.
set -euo pipefail
cd "$(dirname "$0")"
source ./cc_config.sh

if [[ "$HAVQ_VIDEOS_DIR" == *CHANGE_ME* ]]; then
    echo "Edit HAVQ_VIDEOS_DIR in cc_config.sh (and check the other paths) before running this." >&2
    exit 1
fi

module load StdEnv/2023 python/3.11 cuda

if [ ! -d ~/havq-env ]; then
    echo "=== creating venv ~/havq-env ==="
    virtualenv --no-download ~/havq-env
fi
source ~/havq-env/bin/activate
pip install --no-index --upgrade pip

echo "=== installing dependencies ==="
# core deps from the Alliance wheelhouse
pip install --no-index torch torchvision numpy scikit-learn pandas av pillow pyyaml tqdm matplotlib huggingface_hub
# transformers needs to be new enough for V-JEPA2; not in the wheelhouse yet
pip install transformers
# the havq package itself, editable, without letting pip re-resolve deps above
pip install -e . --no-deps

echo "=== downloading backbone weights to $HAVQ_WEIGHTS_DIR ==="
python download_weights.py --models "$HAVQ_WEIGHT_MODELS" --dest "$HAVQ_WEIGHTS_DIR"

echo "=== writing rorqual preprocessing configs ==="
mkdir -p havq/data/preprocessing/configs
for SCALE_INFO in "clip10:10:10" "clip30:30:30" "clip90:90:90"; do
    IFS=":" read -r NAME NFRAME STRIDE <<< "$SCALE_INFO"
    CFG_PATH="havq/data/preprocessing/configs/rorqual_vjepa_${NAME}.yaml"
    cat > "$CFG_PATH" <<EOF
# Preprocessing job (Rorqual): V-JEPA features at ${NFRAME}-frame clips, non-overlapping.
# Generated by cc_initialize.sh from cc_config.sh -- edit cc_config.sh, not this file.
device: "cuda"

paths:
  videos_dir: "${HAVQ_VIDEOS_DIR}"
  features_dir: "${HAVQ_FEATURES_DIR}"

model: "vjepa"
model_weight: "${HAVQ_WEIGHTS_DIR}/${HAVQ_DEFAULT_WEIGHT}"
n_clip_frame: ${NFRAME}
stride: ${STRIDE}
EOF
    echo "wrote $CFG_PATH"
done

echo "=== building $HAVQ_N_SHARDS LPT-balanced shards ==="
python make_shards.py --videos-dir "$HAVQ_VIDEOS_DIR" --n-shards "$HAVQ_N_SHARDS" --out-dir shards

mkdir -p logs
echo "=== done. submit jobs with ./cc_run_jobs.sh ==="
